### ISSUE TITLE
Unclear how to encode form validation errors

### ISSUE THREAD

**Issue by danizen** [uswds/uswds-site#1267]
## Description

Neither the Form component or templates give clear examples of how to encode form validation errors, inline or block, in the USWDS.

## Desired Capability

Description of how to encode and theme form validation errors, both inline and block.   Provide examples in the Form templates.

## Benefits

If USWDS users find their own ways to indicate form errors, or find find classes like `usa-input--error` on their own, it does not lead to design consistency across government web sites.

## Notes

Contrast this with the clear guidance in Bootstrap 3 - https://getbootstrap.com/docs/3.3/css/#forms-control-validation

If there is no consistent way to encode validation, then an appropriate bug should also be opened in the uswds/uswds repository.

**Comment by danizen** [comment]
It is best to leave this as a site issue, as USWDS does have a CSS class for form errors defined in `scss/elements/form-controls/_global.scss`:

```scss
.usa-error-message {
  @include u-padding-y(0.5);
  color: color("error-dark");
  display: block;
  font-weight: font-weight("bold");
}
```
