### ISSUE TITLE
USWDS-Site - Changelog: Decide which data items are required for collected changelogs

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds-site#1787]
Decide which items should be included in the changelog data structure so that we can create a collected changelog that showcases all component and guidance updates.

Prototype sketch:
![Image](https://user-images.githubusercontent.com/93996430/192601158-8ef689dd-ab66-4e6c-b5b4-e1edd4d000fe.png)

Related slack thread: https://gsa-tts.slack.com/archives/C050HRGN7/p1663872299920709

More information can be found in the changelog prototype PR: https://github.com/uswds/uswds-site/pull/1753

**Comment by amyleadem** [comment]
Draft for changelog data items with instructions:
```
changelogURL: [Provide url for the package CHANGELOG.md. Not all pages will have a related CHANGELOG.md file.]
componentPage: [Indicate if the related page is a component, package, or template page. Options: true/false]
title: [Add topic title. This should be only 1-2 words. Ex: "Accessibility", "Banner"]
items:
  - breaking: [Indicate if this is a breaking change. Options: "Yes", "No", "Potential"]
    date: [Add item release date in YYYY-MM-DD format.]
    description:
      summary: [Add a short, clear sentence that summarizes the change. This sentence will link to the related PR.]
      additional: [If needed, add more detail in 1-2 sentences.]
    pr: [Add related pull request (PR) number. Ex: 4695]
    release: [Add related USWDS or package release number. Ex: 3.1.0. Guidance pages will not have a related release.]
    repo: [Declare the GitHub repo that has the related PR. Options: uswds/uswds-site]
    typeCode: [Declare if this update involves component code updates. Options: true/false]
```
