### ISSUE TITLE
Possible browser support issue (Re: autoprefixer)

### ISSUE THREAD

**Issue by fubario** [uswds/uswds-site#793]
Hello, there seems to be a mismatch between the supported browsers listed in .browserslistrc
'> 2%, last 1 version not dead' and uswds design supported browsers 
https://github.com/uswds/uswds/blob/develop/config/gulp/browsers.js, which is 
  '> 2%',  'Last 2 versions',  'IE 11'. This latter value is also used in gulp/sass.js for cssnano https://github.com/uswds/uswds-site/blob/92f942b608ec9810c4fe65ce71c46b41981bb3e7/config/gulp/sass.js#L22 

As a result, it seems like the styles aren't being prefixed as intended.  This is a piece of css from the live site https://designsystem.digital.gov/assets/css/styles.css

```css
  .usa-navbar{
    align-items:center;
    border-bottom:1px solid #e6e6e6;
    display:flex
  }
```

With the updated browserlist config .i.e   '> 2%',  'Last 2 versions',  'IE 11', the same bit of css looks like this 

```css
  .usa-navbar{
    -webkit-box-align:center;
    -ms-flex-align:center;
    align-items:center;
    border-bottom:1px solid #e6e6e6;
    display:-webkit-box;
    display:-ms-flexbox;
    display:flex
  }

```
Not sure if it's supposed to be this way, please ignore if that is the case.
