### ISSUE TITLE
Improve component key/structure in variables.yaml

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-site#974]
The component-based settings are hard to find on our settings page, and it's hard to attach component-based settings to a component page programmatically. Let's add a new key/element to the yaml file to allow better data access.

The current structure uses the `name` key, and isn't clear enough:

```yaml
    - name: Header
      section: true
      subsection: Font family
      description:
      var: $theme-header-font-family
      default: "'ui'"
      kind: family
```

Let's look at restructuring the yaml file to be more useful and easier to read.
